### ISSUE TITLE
РК1 - Мезин

### ISSUE THREAD

**Issue by iketari** [frontend-park-mail-ru/2017_1_Polyhedron#17]
- [x] нужно перейти на компонентный подход, pug-шаблон должен быть сущностью компоенты, а не страницы
- [x] клиент-сайд шаблонизацию должны понимать back-end разработчики
- [x] подумать над файловой структурой
- [x] завести ES2015 Modules в webpack

**Comment by Antonboom** [comment]
Исправлено.
